# Generated by Django 6.0.2 on 2026-03-01 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentbudget',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionallocation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetcategory'),
        ),
        migrations.AddField(
            model_name='sectionallocation',
            name='department_budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.departmentbudget'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.sectionallocation'),
        ),
        migrations.AlterUniqueTogether(
            name='departmentbudget',
            unique_together={('department', 'financial_year')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionallocation',
            unique_together={('department_budget', 'category')},
        ),
    ]
