# Generated by Django 6.0.2 on 2026-03-01 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentbudget',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentbudget',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Principal_Approved', 'Principal Approved'), ('CEO_Approved', 'CEO Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
