# Generated by Django 6.0.2 on 2026-03-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_departmentbudget_approved_by_departmentbudget_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensetransaction',
            options={'ordering': ['-date']},
        ),
    ]
