# Generated by Django 6.0.2 on 2026-03-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('reorder_threshold', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationeryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('HOD_Approved', 'HOD Approved'), ('Principal_Approved', 'Principal Approved'), ('CEO_Approved', 'CEO Approved'), ('Rejected', 'Rejected'), ('Issued', 'Issued')], default='Pending', max_length=20)),
            ],
        ),
    ]
